# Generated by Django 2.2.3 on 2019-07-09 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ödül',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='yayın',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, db_column='TEL', default='+905** *** ** **', max_length=13, null=True, verbose_name='Tel')),
                ('birim', models.CharField(choices=[('Eğitim Fakültesi', 'Eğitim Fakültesi'), ('Fen Edebiyat Fakültesi', 'Fen Edebiyat Fakültesi'), ('İktisadi ve İdari Birimler Fakültesi', 'İktisadi ve İdari Birimler Fakültesi'), ('İslami İlimler Fakültesi', 'İslami İlimler Fakültesi'), ('Eğitim Fakültesi', 'Eğitim Fakültesi'), ('Tıp Fakültesi', 'Tıp Fakültesi'), ('Patnos Sultan Alparslan Doğa Bilimleri ve Mühendislik Fakültesi', 'Patnos Sultan Alparslan Doğa Bilimleri ve Mühendislik Fakültesi'), ('Sağlık Yüksek Okulu', 'Sağlık Yüksek Okulu'), ('Beden Eğitimi ve Spor Yüksekokulu', 'Beden Eğitimi ve Spor Yüksekokulu'), ('Eleşkirt Celal Oruç Hayvansal Üretim Yüksekokulu', 'Eleşkirt Celal Oruç Hayvansal Üretim Yüksekokulu'), ('Yabancı Diller Yüksekokulu', 'Yabancı Diller Yüksekokulu'), ('Turizm İşletmeciliği ve Otelcilik Yüksekokulu', 'Turizm İşletmeciliği ve Otelcilik Yüksekokulu'), ('Patnos Sosyal Hizmetler Yüksekokulu', 'Patnos Sosyal Hizmetler Yüksekokulu'), ('Meslek Yüksekokulu', 'Meslek Yüksekokulu'), ('Sağlık Hizmetleri Meslek Yüksekokulu', 'Sağlık Hizmetleri Meslek Yüksekokulu'), ('Eleşkirt Meslek Yüksekokulu', 'Eleşkirt Meslek Yüksekokulu'), ('Doğubayazıt Ahmed-i Hani Meslek Yüksekokulu', 'Doğubayazıt Ahmed-i Hani Meslek Yüksekokulu'), ('Sivil Havacılık Meslek Yüksekokulu', 'Sivil Havacılık Meslek Yüksekokulu'), ('Patnos Meslek Yüksekokulu', 'Patnos Meslek Yüksekokulu'), ('Fen Bilimleri Enstitüsü', 'Fen Bilimleri Enstitüsü'), ('Sosyal Bilimler Enstitüsü', 'Sosyal Bilimler Enstitüsü'), ('Sağlık Bilimleri Enstitüsü', 'Sağlık Bilimleri Enstitüsü')], db_column='BİRİM', max_length=150, verbose_name='Birim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Ayarları',
            },
        ),
        migrations.CreateModel(
            name='faliyet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='atıf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih')),
                ('tür', models.CharField(blank=True, choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', max_length=20, null=True, verbose_name='Tür')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='dosyalar')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
