# Generated by Django 2.2.3 on 2019-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yayın',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
    ]
