# Generated by Django 2.2.3 on 2019-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0002_auto_20190710_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', null=True, verbose_name='Tarih'),
        ),
    ]
