# Generated by Django 2.2.3 on 2019-07-11 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0006_auto_20190711_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='tarih',
            field=models.DateTimeField(db_column='Tarih', default=datetime.date.today, verbose_name='Tarih'),
        ),
    ]
