# Generated by Django 2.2.3 on 2019-07-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0007_auto_20190711_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_column='Tarih', verbose_name='Tarih'),
        ),
    ]
