# Generated by Django 2.2.3 on 2019-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0011_auto_20190711_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='tarih',
            field=models.CharField(db_column='Tarih', default='yyyy-aa-gg', max_length=10, verbose_name='Tarih'),
        ),
    ]
