# Generated by Django 2.2.3 on 2019-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0014_auto_20190717_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='atıf',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='ISI Dergilerindeki Atıflar', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='Kongre Sempozyumu', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='Baş Editör', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='Patent', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='TÜBİTAK Projesi', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='ISI Makale', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='dosya',
            field=models.FileField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='dosyalar'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='tür',
            field=models.CharField(choices=[('ISI Makale', 'ISI Makale'), ('Diğer Makale', 'Diğer Makale'), ('Kitap', 'Kitap'), ('Kitapta Bölüm', 'Kitapta Bölüm'), ('Bildiri', 'Bildiri'), ('Ansiklopedi konusu', 'Ansiklopedi konusu'), ('Diğer', 'Diğer')], db_column='TÜR', default='Proje ödülü', max_length=20, null=True, verbose_name='Tür'),
        ),
    ]
