# Generated by Django 2.2.3 on 2019-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0015_auto_20190717_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atıf',
            name='tür',
            field=models.CharField(db_column='TÜR', default='ISI Dergilerindeki Atıflar', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tür',
            field=models.CharField(db_column='TÜR', default='Kongre Sempozyumu', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='faliyet',
            name='tür',
            field=models.CharField(db_column='TÜR', default='Baş Editör', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tür',
            field=models.CharField(db_column='TÜR', default='Patent', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='tür',
            field=models.CharField(db_column='TÜR', default='TÜBİTAK Projesi', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='tür',
            field=models.CharField(db_column='TÜR', default='ISI Makale', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='ödül',
            name='tür',
            field=models.CharField(db_column='TÜR', default='Proje ödülü', max_length=20, null=True, verbose_name='Tür'),
        ),
    ]
