# Generated by Django 2.2.3 on 2019-07-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0016_auto_20190719_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusermodel',
            name='birim',
            field=models.CharField(choices=[('Eğitim Fakültesi', 'Eğitim Fakültesi'), ('Fen Edebiyat Fakültesi', 'Fen Edebiyat Fakültesi'), ('İktisadi ve İdari Birimler Fakültesi', 'İktisadi ve İdari Birimler Fakültesi'), ('İslami İlimler Fakültesi', 'İslami İlimler Fakültesi'), ('Tıp Fakültesi', 'Tıp Fakültesi'), ('Patnos Sultan Alparslan Doğa Bilimleri ve Mühendislik Fakültesi', 'Patnos Sultan Alparslan Doğa Bilimleri ve Mühendislik Fakültesi'), ('Sağlık Yüksek Okulu', 'Sağlık Yüksek Okulu'), ('Beden Eğitimi ve Spor Yüksekokulu', 'Beden Eğitimi ve Spor Yüksekokulu'), ('Eleşkirt Celal Oruç Hayvansal Üretim Yüksekokulu', 'Eleşkirt Celal Oruç Hayvansal Üretim Yüksekokulu'), ('Yabancı Diller Yüksekokulu', 'Yabancı Diller Yüksekokulu'), ('Turizm İşletmeciliği ve Otelcilik Yüksekokulu', 'Turizm İşletmeciliği ve Otelcilik Yüksekokulu'), ('Patnos Sosyal Hizmetler Yüksekokulu', 'Patnos Sosyal Hizmetler Yüksekokulu'), ('Meslek Yüksekokulu', 'Meslek Yüksekokulu'), ('Sağlık Hizmetleri Meslek Yüksekokulu', 'Sağlık Hizmetleri Meslek Yüksekokulu'), ('Eleşkirt Meslek Yüksekokulu', 'Eleşkirt Meslek Yüksekokulu'), ('Doğubayazıt Ahmed-i Hani Meslek Yüksekokulu', 'Doğubayazıt Ahmed-i Hani Meslek Yüksekokulu'), ('Sivil Havacılık Meslek Yüksekokulu', 'Sivil Havacılık Meslek Yüksekokulu'), ('Patnos Meslek Yüksekokulu', 'Patnos Meslek Yüksekokulu'), ('Fen Bilimleri Enstitüsü', 'Fen Bilimleri Enstitüsü'), ('Sosyal Bilimler Enstitüsü', 'Sosyal Bilimler Enstitüsü'), ('Sağlık Bilimleri Enstitüsü', 'Sağlık Bilimleri Enstitüsü')], db_column='BİRİM', max_length=150, verbose_name='Birim'),
        ),
    ]
