# Generated by Django 2.2.3 on 2019-07-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0019_auto_20190721_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yayın',
            name='akademisyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yayın',
            name='tür',
            field=models.CharField(db_column='TÜR', default='ISI Dergilerinde Makale', max_length=100, null=True, verbose_name='Tür'),
        ),
    ]
