# Generated by Django 2.2.3 on 2019-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bys', '0022_auto_20190722_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusermodel',
            name='tel',
            field=models.CharField(blank=True, db_column='TEL', default='+905** *** ** **', max_length=16, null=True, verbose_name='Tel'),
        ),
    ]
